all:    monte_pi_sprng
monte_pi_sprng:   monte_pi_sprng.o plot.o
	echo "1 missisipi\n"
        
monte_pi_sprng.o: /usr/local/lib/sprng/include/sprng.h /usr/local/lib/pgplot/cpgplot.h monte_pi_sprng.c
	echo "2 missisipi"
       
plot.o: /usr/local/lib/pgplot/cpgplot.h plot.c
	echo "3 missisipi"

