all:    monte_pi_sprng
monte_pi_sprng:   monte_pi_sprng.o plot.o
	echo "1 missisipi\n"

monte_pi_sprng.o: monte_pi_sprng.c
	touch monte_pi_sprng.o
	echo "2 missisipi\n"

plot.o: plot.c
	touch "plot.o"
	echo "3 missisipi"
	echo "4 missisipi\n"

